[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
zkSyncSepoliaTestnet = "https://sepolia.era.zksync.dev"
anvilZKsync = "http://127.0.0.1:8011"
sophonTestnet = "https://rpc.testnet.sophon.xyz"
sophonMainnet = "https://rpc.sophon.xyz"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
